baseURL = 'http://handbook.morethancode.plus/'
languageCode = 'zh-cn'
title = '开源社区治理工作手册'
enableEmoji = true
# enableGitInfo = true

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup]
    [markup.tableOfContents]
      endLevel = 3
      startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # https://jdhao.github.io/2019/12/29/hugo_html_not_shown/
  # [markup.highlight]
  #   codeFences = false # disables Hugo's default syntax highlighting
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true

[[menu.primary]]
    name  = "手册"
    url = "/docs/"
    identifier = "docs"
    weight = 10

# [[menu.primary]]
#     name  = "Showcase"
#     url = "/showcase"
#     identifier = "showcase"
#     weight = 20

[[menu.primary]]
    name  = "反馈"
    url = "https://atomgit.com/OpenAtomFoundation/OpenSource_Governance"
    identifier = "community"
    weight = 30

[params]

  # Google Fonts
  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font = "Inter"     # Default is System font
  secondary_font  = "Inter"     # Default is System font
  mono_font       = "Fira Code" # Default is System font

    [params.footer]
        copyright = "© :YEAR: OpenAtom Foundation. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
        version   = true # include git commit info in footer

    [params.social]
        github = "sunny0826/community-handbook" # github.com/YOUR_GITHUB_ID
        twitter = "guoxudong_"            # twitter.com/YOUR_TWITTER_ID
        # instagram = ""      # instagram.com/YOUR_INSTAGRAM_ID
        rss = true                     # show rss icon with link

    [params.docs] # Parameters for the /docs 'template'
        title           = "Community Handbook"                        # default html title for documentation pages/sections

        # pathName        = "handbook"                            # path for documentation site | default "docs"

        themeColor      = "blue"                            # (optional) - Set theme accent colour. Options include: blue (default), green, red, yellow, emerald, cardinal, magenta, cyan

        darkMode        = true                                # enable dark mode option? default false

        prism           = true                                # enable syntax highlighting via Prism

        # prismTheme      = "lotusdocs"                         # (optional) - Set theme for PrismJS. Options include: lotusdocs (default), solarized-light, twilight, lucario

        # gitinfo
        repoURL         = "https://github.com/sunny0826/community-handbook"  # Git repository URL for your site [support for GitHub, GitLab, and BitBucket]
        repoBranch      = "release"                           # Name of your Git repository branch
        editPage        = true                                # enable 'Edit this page' feature - default false
        lastMod         = true                                # enable 'Last modified' date on pages - default false
        lastModRelative = true                                # format 'Last modified' time as relative - default true

        # ToC
        toc             = true                                # enable table of contents? default is true
        tocMobile       = true                                # enable table of contents in mobile view? default is true
        scrollSpy       = true                                # enable scrollspy on ToC? default is true

        # icons
        sidebarIcons    = true                                # enable sidebar icons? default false
        titleIcon       = true                                # enable front matter icon title prefix? default is false

        # content navigation
        breadcrumbs     = true                                # default is true
        navDesc         = true                                # include front matter descriptions in Prev/Next navigation cards
        navDescTrunc    = 30                                  # Number of characters by which to truncate the Prev/Next descriptions

        listDescTrunc   = 100                                 # Number of characters by which to truncate the list card description
        backToTop       = true                                # enable back-to-top button? default true

        # front matter
        descriptions    = true                                # enable front matter descriptions under content title?

        # Link behaviour
        intLinkTooltip  = true                                # Enable a tooltip for internal links that displays info about the destination? default false
        # extLinkNewTab   = false                               # Open external links in a new Tab? default true
        logoLinkURL = "https://atomgit.com/OpenAtomFoundation/OpenSource_Governance"                                      # Set a custom URL destination for the top header logo link.

    [params.flexsearch] # Parameters for FlexSearch
        enabled             = true
        # tokenize            = "full"
        # optimize            = true
        # cache               = 100
        # minQueryChar        = 3 # default is 0 (disabled)
        # maxResult           = 5 # default is 5
        # searchSectionsIndex = []
